// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvDjkv2y-WdzonsBvtP2CFJOL33HHSmMU',
    appId: '1:376115287951:web:2da332dba75b2802895dfa',
    messagingSenderId: '376115287951',
    projectId: 'final-year-project-5fc77',
    authDomain: 'final-year-project-5fc77.firebaseapp.com',
    storageBucket: 'final-year-project-5fc77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMwuRaJxZAGY_oVlGZAzcDLMnydaHBcJE',
    appId: '1:376115287951:android:eb4006436cc5ad45895dfa',
    messagingSenderId: '376115287951',
    projectId: 'final-year-project-5fc77',
    storageBucket: 'final-year-project-5fc77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKrwLNvRKvetBZaHyKWZtHGRI5LO2FisM',
    appId: '1:376115287951:ios:a34af2f8bd2f7dec895dfa',
    messagingSenderId: '376115287951',
    projectId: 'final-year-project-5fc77',
    storageBucket: 'final-year-project-5fc77.firebasestorage.app',
    iosBundleId: 'com.example.pokemonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKrwLNvRKvetBZaHyKWZtHGRI5LO2FisM',
    appId: '1:376115287951:ios:a34af2f8bd2f7dec895dfa',
    messagingSenderId: '376115287951',
    projectId: 'final-year-project-5fc77',
    storageBucket: 'final-year-project-5fc77.firebasestorage.app',
    iosBundleId: 'com.example.pokemonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvDjkv2y-WdzonsBvtP2CFJOL33HHSmMU',
    appId: '1:376115287951:web:da05ff4dfb0b350b895dfa',
    messagingSenderId: '376115287951',
    projectId: 'final-year-project-5fc77',
    authDomain: 'final-year-project-5fc77.firebaseapp.com',
    storageBucket: 'final-year-project-5fc77.firebasestorage.app',
  );
}
